### ISSUE TITLE
点击下载后，阅读器界面显示“读取数据失败”

### ISSUE THREAD

**Issue by miruku-neko** [cpuopt/DLsite-Play-Downloader#13]
![image](https://github.com/user-attachments/assets/2153739b-207c-4e37-afcd-d44f79a2dcfb)
单独点开阅读器浏览，图片能够正常显示。
点击使用脚本下载后，阅读器黑屏，并出现如图报错。
返回目录，下载器卡在“准备前往阅读器获取URL…”。
实验的作品直到2024年8月末都能使用脚本正常下载，今天再点击就报错了。

**Comment by miruku-neko** [comment]
应该不是个别情况，以前所有能下载的漫画现在都报错了

**Comment by lenzdz** [comment]
Hey, there! 

I'm having the same issue here. Other downloaders are also failing, so I'm guessing the site's structure changed and that's why the extension isn't able to fetch correctly.
![DLsite-Play-Google-Chrome-2024-09-22-21-30-22](https://github.com/user-attachments/assets/e6c48495-80b5-4fb0-a310-8a7cbc585276)

**Comment by cpuopt** [comment]
已更新1.6版本，请尝试。
https://github.com/cpuopt/DLsite-Play-Downloader/commit/3324a56f297c49566abf36bf8bf1f0ca437f1eea
推测原因为dlsitePlay对原生fetch进行了封装和覆盖，导致脚本获取到的fetch函数是被覆盖后的，并且它不是异步函数，不能使用await关键字获取响应。所以脚本改为了promise语法，应该已经解决了这个问题。

**Comment by miruku-neko** [comment]
非常感谢，已经可以正常下载了
