### ISSUE TITLE
以 100% 质量提取图像 (Extract Images With 100% Quality)

### ISSUE THREAD

**Issue by Jay123210599** [cpuopt/DLsite-Play-Downloader#7]
我到底如何使用这个工具? 如何使用它来提取包含我购买的漫画的页面，而不会损失任何质量? (How do I use this tool, exactly? How do I use this to extract pages with my purchased mangas exactly as they are, without losing any quality?) 
https://www.dlsite.com/comic/work/=/product_id/BJ348612.html

https://play.dlsite.com/csr/viewer/hybrid?cgi=https%3A%2F%2Fplay.dl.dlsite.com%2Fcsr%2Fapi%2Fdiazepam_hybrid.php&customer_id=SFT000011075079&param=EIjKOjwT4CIIDCdEDirZh2OUisz%2BtTRP32jOXsug0lTLFCCi8V5Erqk2vJJIoLDdLXnK5CwL9mGDEPrWPaWmHgINTHnK2%2BmmRGG2mUUggg%2Bt1t3MwmACVFA0VvbBP83OyQsydW8%2F5AcV9ZLZT%2BA4yMDjCb4FE%2BVqaFD4rk3d1z8XZE7o3B%2FgqGzyLds0fESsDDPK5movVryfdy%2F2kZo%2FCHyL5OV7PaXkGgP8CdX1v0dnoHlSescoe4KRz%2FOA8alovETGyBzFnCSCFh%2Fh3%2FT1b6lpqBFbVDUlVklOTvOFmBxVFvyZ9ct5gI4%2FJBQPtg2v95rgcjJFslD8%2BmHBPSYzhnOgMWyTmF7QQb8BCNCVRXltmbLJe8xhbqypD5ukLUO0KI1%2FFuLQM8GLktHZ9Ymnqg%3D%3D&workno=BJ348612

![DLsite](https://github.com/cpuopt/DLsite-Play-Downloader/assets/141977822/cbd935b6-6b59-4021-a592-c6204246e4f7)

**Comment by cpuopt** [comment]
First, install [Tampermonkey](https://chromewebstore.google.com/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=zh-CN&utm_source=ext_sidebar).

Then, click [Install from Greasy Fork](https://greasyfork.org/zh-CN/scripts/480281-dlsite-play-downloader) on the readme page, and click “Install” in both Greasy Fork and Tampermonkey.


Navigate to the DLsite Play page of the manga you want to download, ensuring the plugin is enabled, as shown below:

![Plugin Enabled Screenshot](https://github.com/cpuopt/DLsite-Play-Downloader/assets/46257373/b34c9d93-3f2f-45dd-9406-4e34c4c4ccfe)

The download button should appear on the page as shown below:

![Download Button Screenshot](https://github.com/cpuopt/DLsite-Play-Downloader/assets/46257373/48bcc7e7-d7e7-4890-92c1-384ac3d1b4a6)

Additionally, extracting images at 100% quality is not feasible because the images provided by DLsite Play are like this:

![Example Image](https://github.com/cpuopt/DLsite-Play-Downloader/assets/46257373/87d664d5-b7e7-4509-a1dc-976c08c5c7e3)

Cropping and stitching are necessary, a process that cannot guarantee lossless quality. However, saving the stitched images as PNG will maintain a lossless format.
